#%RAML 1.0
title: areadenegocio-nomedaaplicacao-camadadeexposicao
description: areadenegocio-nomedaaplicacao-camadadeexposicao
version: v1
mediaType: application/json

uses:
  global-resources-fragments: /exchange_modules/f8f9abd2-10a0-400f-bb5b-60cbd5b8cb29/global-resources-fragments/1.0.0/global-resources-fragments.raml
  fragments-areadenegocio: exchange_modules/f8f9abd2-10a0-400f-bb5b-60cbd5b8cb29/areadenegocio-nomedaaplicacao-fragment/1.0.0/areadenegocio-nomedaaplicacao-fragment.raml
/customers:
  description: Base resource for accessing customer information.
  /{customerId}:
    description: Manage information for a specific customer.
    is: [ global-resources-fragments.ErrorResponses ]
    securedBy:  
    - global-resources-fragments.client-enforcement
    - global-resources-fragments.basic-authentication
    - global-resources-fragments.oauth_2_0
    get:
      description: Return details for an existing customer.
      responses:
        200:
          body:
            application/json:
              type: fragments-areadenegocio.get-customers-by-id
  post:
    is: [ global-resources-fragments.ErrorResponses ]
    securedBy:  
    - global-resources-fragments.client-enforcement
    body:
      application/json:
        type: fragments-areadenegocio.post-customers-request
    responses:
      200:
        body:
          application/json:
            type: fragments-areadenegocio.post-customers-response